---
name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * 1,3,5'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install roboRIO toolchain
        run: ./gradlew --console=plain installRoboRioToolchain
      - name: Build
        run: ./gradlew --console=plain clean build

  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check formatted correctly
        uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: './src/main/cpp ./src/main/include'
          clangFormatVersion: 6
...
